name: ${project.name}
author: OffLuffy
description: ${project.description}
version: ${project.version}
main: ${project.groupId}.${project.name}.${project.name}
api-version: 1.13
commands:
  glowfellerreload:
    description: Reloads GlowFeller's config
    permission: glowfeller.reload
    usage: /gfreload
    aliases: [gfreload]
permissions:
  glowfeller.reload:
    description: Allows you to reload GlowFeller's config with /gfreload
    default: op